services:
  mysql-db:
    image: mysql:8.4.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ms-produto:
    build: .
    restart: always
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/produtos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"

volumes:
  mysql_data: